name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version:
          - "5.1.:latest"
          - "5.2.:latest"
          - "5.3.:latest"
          - "5.4.:latest"
          - "lj-v2.1:latest"

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Setup Lua ${{ matrix.lua-version }}
      uses: mah0x211/setup-lua@v1
      with:
        versions: ${{ matrix.lua-version }}
    -
      name: Install Tools
      run: |
        sudo apt install lcov -y
        luarocks install testcase
    -
      name: Install
      run: |
        luarocks make RECO_COVERAGE=1
    -
      name: Run Test
      run: |
        testcase ./test
    -
      name: Generate coverage reports
      run: |
        sh ./covgen.sh
    -
      name: Upload C coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
